import type { ChartState, StudioPreset } from "../types";

export const DEFAULT_CHART_STATE: ChartState = {
  title: "Revenue momentum",
  description: "Quarterly revenue by channel with visible labels, legend, and chart summary.",
  label: "Revenue",
  helper: "Preview and exported JSX render the same chart anatomy.",
  id: "revenue-momentum-chart",
  ariaLabel: "Revenue momentum chart",
  ariaDescription: "Bar chart comparing revenue across six monthly categories.",
  tabIndex: 0,
  width: 560,
  height: 380,
  gap: 16,
  padding: 24,
  radius: 28,
  borderWidth: 1,
  shadow: 28,
  background: "#0f172a",
  foreground: "#e5eefb",
  muted: "#94a3b8",
  accent: "#38bdf8",
  border: "#334155",
  fontFamily: "Inter",
  titleSize: 24,
  bodySize: 14,
  fontWeight: 800,
  previewState: "default",
  motion: true,
  disabled: false,
  role: "img",
  chartType: "bar",
  seriesCount: 3,
  dataPoints: 6,
  showLegend: true,
  showTooltip: true,
  showGrid: true,
  valueFormat: "compact",
};

const base = DEFAULT_CHART_STATE;

const preset = (
  id: string,
  family: string,
  archetype: string,
  variant: string,
  size: string,
  tags: string[],
  state: Partial<ChartState>,
): StudioPreset => ({
  id,
  family,
  archetype,
  variant,
  size,
  tags,
  state: { ...base, ...state },
});

export const CHART_PRESETS: StudioPreset[] = [
  preset("revenue-bars-dark", "revenue", "Executive", "bar", "standard", ["bar", "legend", "grid", "labels"], {
    title: "Revenue momentum",
    description: "Quarterly revenue by channel with visible labels and grid lines.",
    ariaLabel: "Revenue momentum bar chart",
    ariaDescription: "Bar chart showing six revenue categories across three series.",
    chartType: "bar",
    seriesCount: 3,
    dataPoints: 6,
    accent: "#38bdf8",
    background: "#0f172a",
    foreground: "#e5eefb",
    muted: "#94a3b8",
    border: "#334155",
    valueFormat: "compact",
  }),
  preset("conversion-line-light", "conversion", "Growth", "line", "wide", ["line", "trend", "percent", "tooltip"], {
    title: "Conversion trend",
    description: "A percent-based line chart with categorical month labels.",
    label: "Conversion",
    helper: "Hover state can reveal a deterministic tooltip preview.",
    ariaLabel: "Conversion trend line chart",
    ariaDescription: "Line chart showing conversion percentages over eight months.",
    chartType: "line",
    seriesCount: 1,
    dataPoints: 8,
    width: 640,
    height: 400,
    background: "#f8fafc",
    foreground: "#0f172a",
    muted: "#475569",
    accent: "#2563eb",
    border: "#cbd5e1",
    valueFormat: "percent",
    previewState: "hover",
  }),
  preset("channel-donut", "channel", "Marketing", "donut", "standard", ["donut", "parts", "total", "legend"], {
    title: "Channel mix",
    description: "Donut chart with segment labels and total value in the center.",
    label: "Channel",
    ariaLabel: "Channel mix donut chart",
    ariaDescription: "Donut chart comparing channel contribution across five categories.",
    chartType: "donut",
    seriesCount: 1,
    dataPoints: 5,
    background: "#042f2e",
    foreground: "#ccfbf1",
    muted: "#5eead4",
    accent: "#2dd4bf",
    border: "#0f766e",
    valueFormat: "number",
  }),
  preset("pipeline-bars", "pipeline", "Sales", "bar", "compact", ["bar", "compact", "sales"], {
    title: "Pipeline health",
    description: "Compact bar chart for pipeline stages and values.",
    label: "Pipeline",
    ariaLabel: "Pipeline health bar chart",
    ariaDescription: "Compact bar chart displaying five pipeline stages.",
    width: 440,
    height: 300,
    padding: 18,
    chartType: "bar",
    seriesCount: 2,
    dataPoints: 5,
    accent: "#f97316",
    valueFormat: "compact",
  }),
  preset("support-line", "support", "Operations", "line", "standard", ["line", "support", "success-state"], {
    title: "Resolution time",
    description: "Line chart for support resolution values with live-data state badge.",
    label: "Resolution",
    ariaLabel: "Resolution time line chart",
    ariaDescription: "Line chart showing seven support resolution data points.",
    chartType: "line",
    seriesCount: 1,
    dataPoints: 7,
    accent: "#22c55e",
    previewState: "success",
    valueFormat: "number",
  }),
  preset("retention-empty", "retention", "Product", "empty", "standard", ["empty", "state", "honest"], {
    title: "Retention cohort",
    description: "Empty state preview for a chart without available cohort data.",
    label: "Cohort",
    ariaLabel: "Retention cohort chart empty state",
    ariaDescription: "Empty state for a retention cohort chart with no data points.",
    chartType: "bar",
    dataPoints: 0,
    previewState: "empty",
    showLegend: false,
  }),
  preset("forecast-loading", "forecast", "Finance", "loading", "standard", ["loading", "state"], {
    title: "Forecast loading",
    description: "Loading state while forecast data is requested.",
    label: "Forecast",
    ariaLabel: "Forecast chart loading state",
    ariaDescription: "Loading state for a forecast chart.",
    chartType: "line",
    previewState: "loading",
    dataPoints: 6,
  }),
  preset("quality-error", "quality", "Reliability", "error", "standard", ["error", "state"], {
    title: "Quality score",
    description: "Error state for failed chart data retrieval.",
    label: "Quality",
    ariaLabel: "Quality score chart error state",
    ariaDescription: "Error state for a quality score chart.",
    chartType: "donut",
    previewState: "error",
    background: "#1f1114",
    foreground: "#fee2e2",
    muted: "#fca5a5",
    accent: "#ef4444",
    border: "#7f1d1d",
  }),
  preset("inventory-bars-light", "inventory", "Commerce", "bar", "wide", ["bar", "commerce", "wide"], {
    title: "Inventory by region",
    description: "Wide bar chart with eight categories and value labels.",
    label: "Inventory",
    ariaLabel: "Inventory by region bar chart",
    ariaDescription: "Wide bar chart comparing inventory counts across regions.",
    chartType: "bar",
    seriesCount: 4,
    dataPoints: 8,
    width: 680,
    height: 420,
    background: "#fff7ed",
    foreground: "#431407",
    muted: "#9a3412",
    accent: "#ea580c",
    border: "#fed7aa",
    valueFormat: "number",
  }),
  preset("engagement-donut-light", "engagement", "Community", "donut", "wide", ["donut", "community", "light"], {
    title: "Engagement share",
    description: "Donut visualization for community engagement categories.",
    label: "Engagement",
    ariaLabel: "Engagement share donut chart",
    ariaDescription: "Donut chart showing engagement share across six categories.",
    chartType: "donut",
    dataPoints: 6,
    width: 640,
    height: 420,
    background: "#fdf2f8",
    foreground: "#500724",
    muted: "#be185d",
    accent: "#db2777",
    border: "#fbcfe8",
    valueFormat: "percent",
  }),
  preset("latency-line-dark", "latency", "Platform", "line", "compact", ["line", "platform", "compact"], {
    title: "Latency budget",
    description: "Compact line chart for platform latency snapshots.",
    label: "Latency",
    ariaLabel: "Latency budget line chart",
    ariaDescription: "Line chart showing six latency budget points.",
    chartType: "line",
    dataPoints: 6,
    width: 460,
    height: 320,
    accent: "#a78bfa",
    background: "#18181b",
    foreground: "#fafafa",
    muted: "#a1a1aa",
    border: "#3f3f46",
    valueFormat: "number",
  }),
  preset("margin-bars-no-grid", "margin", "Finance", "bar", "minimal", ["bar", "minimal", "no-grid"], {
    title: "Margin profile",
    description: "Minimal bar chart without grid or tooltip preview.",
    label: "Margin",
    ariaLabel: "Margin profile bar chart",
    ariaDescription: "Minimal bar chart comparing margin values.",
    chartType: "bar",
    seriesCount: 1,
    dataPoints: 5,
    showGrid: false,
    showTooltip: false,
    showLegend: false,
    background: "#f8fafc",
    foreground: "#0f172a",
    muted: "#475569",
    accent: "#0f766e",
    border: "#cbd5e1",
    valueFormat: "percent",
  }),
];
